name: Build Nightly

on:
#  push:
#    branches:
#      - feature/*
  workflow_run:
    workflows: ["Unit Test"]
    branches:
      - feature/*
      - release/*
      - develop
      - main
    types:
      - completed

jobs:
  docker-image-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project

    - name: Show extracted Maven project version
      run: echo ${{ steps.project.outputs.version }}

    - name: branch
      run: git branch
