name: Build Nightly

on:
#  push:
#    branches:
#      - feature/*
  workflow_run:
    workflows: ["Unit Test"]
    branches:
      - feature/*
      - release/*
      - develop
      - main
    types:
      - completed

jobs:
  docker-image-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      # Get version from pom.xml
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project

      - name: Show extracted Maven project version
        run: echo ${{ steps.project.outputs.version }}
- name: branch
        run: git branch
